# Generated by Django 5.2 on 2025-04-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20250416_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'TV Series'), ('anime', 'Anime'), ('documentary', 'Documentary'), ('shortfilm', 'Short Film'), ('cartoon', 'Cartoon')], max_length=20),
        ),
    ]
